### ISSUE TITLE
Traffic Cop - Learn Load Balancer using HAProxy

### ISSUE THREAD

**Issue by jain-yakshit-1** [Crio-Bytes/System-Design#4]
**MicroByte Title:** Traffic Cop - Learn Load Balancer using HAProxy

**Domain:** System Design, Networking

**Scope of learning for learners:** Learners will get an idea of how the systems in the real world are made scalable and handle millions of requests by routing the requests to various machines in the cluster using Load Balancer.

**Activities:** The MicroByte activities will start with 1) Experience real-world load balancer of google.com
2) Installation of HA-proxy
3) Launch server applications with different ports.
4)  Configure HA-Proxy to load balance server with different load balancing strategies.

**Comment by amoghrajesh** [comment]
Hey @jnana-cetana. We have assigned this issue to you. 
You can start working on this. Please keep in mind the learn by doing methodology and we can't wait to review this one 😄 
All the best!

**Comment by jain-yakshit-1** [comment]
Completed the Creation of Micro-Byte. Please have a look!
